### ISSUE TITLE
Internal bluetooth adapter of Raspberry Pi 3 cannot be powered on within docker container

### ISSUE THREAD

**Issue by pouldam** [pfink/nuimo-openhab-python#1]
Thanks for working on this project!

Having just bought a Nuimo and already using openHAB, I wanted to try out your project, but quickly ran into a problem. I hope you can help.

I did the following:

1. Wiped my Raspberry Pi 3 B
2. Reinstalled Raspbian using NOOBS
3. Using SSH (as root) I followed the exact instructions in your readme - using the Docker-approach.
4. When trying to start the Docker container it stops by itself, and the log gives me the following:

I am not exactly a Linux or Rasberry Pi wiz, so sorry if the error is obvious or on me :-)

```
Starting system message bus: dbus.
[bluetooth]# power on bluetoothd...
No default controller available
(bluetoothctl:31): GLib-CRITICAL **: Source ID 16 was not found when attempting to remove it
\n                                 
{'openhab_api_url': 'http://192.168.8.10:8444/rest', 'bluetooth_adapter': 'hci0', 'default_gesture_command_mapping': {'TOUCH_BOTTOM': 'OFF', 'BUTTON_RELEASE': 'ON', 'TOUCH_RIGHT': 'NEXT', 'TOUCH_LEFT': 'PRE
VIOUS'}, 'nuimo_mac_address': 'DD:7F:88:8C:06:D3'}
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
http.client.BadStatusLine: ''
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
    _pool=self, _stacktrace=stacktrace)
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
    response.begin()
  File "/usr/lib/python3.4/http/client.py", line 351, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
    raise BadStatusLine(line)
urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    apps = OpenHabAppBuilder().buildApps(openhab)
  File "/opt/nuimo-openhab-python/nuimo_openhab/app_builder.py", line 8, in buildApps
    nuimoGroupItem = openhab.req_get("/items/"+rootItemName)
  File "/usr/local/lib/python3.4/dist-packages/openhab/openhab.py", line 91, in req_get
    r = self.session.get(self.base_url + uri_path)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 469, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by pfink** [comment]
It seems that there is no bluetooth adapter available:
```[bluetooth]# power on bluetoothd...
No default controller available
```
Do you have a bluetooth adapter that is not occupied by the host system?

**Comment by pouldam** [comment]
Thanks a lot for getting back to me! I have not added a bluetooth dongle as I am planning on using the Raspberry Pi 3 Model B's onboard bluetooth Low Energy chip.

If I type `hcitool dev`  on the host, it gives me:

```
Devices:
  hci0   DD:7F:88:8C:06:D3
```

If I type `bluetoothd`  on the host, it gives me:

```
D-Bus setup failed: Name already in use
```

The host is running the version of Bluez (5.23) that came with the Raspbian image downloaded from raspberrypi.org (Raspbian Jessie with desktop). It is my understanding that it does not support BLE, but that problem is addressed by using your Docker container.

Are you using Raspbian? Maybe another Linux distro would solve my problem?

**Comment by pfink** [comment]
Try to stop bluez on the host system before starting the docker container: `service bluetooth stop`

**Comment by pouldam** [comment]
Thanks - that seemed to get me a little further - but still not there:

```
2017-07-02T11:53:42.631925976Z Removing stale PID file /var/run/dbus/pid..
2017-07-02T11:53:42.652538696Z Starting system message bus: dbus.
2017-07-02T11:53:46.728259688Z Waiting to connect to bluetoothd...
[bluetooth] [NEW] Controller B8:27:EB:E5:56:F5 raspberrypi [default]
2017-07-02T11:53:46.736726859Z [bluetooth] power on
2017-07-02T11:53:46.739786176Z [bluetooth] [DEL] Controller B8:27:EB:E5:56:F5 raspberrypi [default]
2017-07-02T11:53:46.744230333Z
2017-07-02T11:53:46.744368875Z (bluetoothctl:31): GLib-CRITICAL **: Source ID 20 was not found when attempting to remove it
2017-07-02T11:53:46.767061225Z [bluetooth] Waiting to connect to bluetoothd...                                   
\n
2017-07-02T11:53:47.730097743Z {'nuimo_mac_address': 'DD:7F:96:8C:06:D3', 'bluetooth_adapter': 'hci0', 'openhab_api_url': 'http://192.168.8.10:8444/rest', 'default_gesture_command_mapping': {'BUTTON_RELEASE': 'ON', 'TOUCH_BOTTOM': 'OFF', 'TOUCH_LEFT': 'PREVIOUS', 'TOUCH_RIGHT': 'NEXT'}}
2017-07-02T11:53:47.751485097Z Traceback (most recent call last):
2017-07-02T11:53:47.751618794Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 331, in _make_request
2017-07-02T11:53:47.751652805Z     httplib_response = conn.getresponse(buffering=True)
2017-07-02T11:53:47.751683742Z TypeError: getresponse() got an unexpected keyword argument 'buffering'
2017-07-02T11:53:47.751714055Z 
2017-07-02T11:53:47.751742804Z During handling of the above exception, another exception occurred:
2017-07-02T11:53:47.751772857Z 
2017-07-02T11:53:47.751801346Z Traceback (most recent call last):
2017-07-02T11:53:47.751833013Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
2017-07-02T11:53:47.751864263Z     body=body, headers=headers)
2017-07-02T11:53:47.751893742Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
2017-07-02T11:53:47.751924783Z     httplib_response = conn.getresponse()
2017-07-02T11:53:47.751954367Z   File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
2017-07-02T11:53:47.751984731Z     response.begin()
2017-07-02T11:53:47.752013533Z   File "/usr/lib/python3.4/http/client.py", line 351, in begin
2017-07-02T11:53:47.752044158Z     version, status, reason = self._read_status()
2017-07-02T11:53:47.752073689Z   File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
2017-07-02T11:53:47.752104210Z     raise BadStatusLine(line)
2017-07-02T11:53:47.752133377Z http.client.BadStatusLine: ''
2017-07-02T11:53:47.752162335Z 
2017-07-02T11:53:47.752190929Z During handling of the above exception, another exception occurred:
2017-07-02T11:53:47.752220668Z 
2017-07-02T11:53:47.752248845Z Traceback (most recent call last):
2017-07-02T11:53:47.752278064Z   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 362, in send
2017-07-02T11:53:47.752309262Z     timeout=timeout
2017-07-02T11:53:47.752338376Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 559, in urlopen
2017-07-02T11:53:47.752413011Z     _pool=self, _stacktrace=stacktrace)
2017-07-02T11:53:47.752443793Z   File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 245, in increment
2017-07-02T11:53:47.752474991Z     raise six.reraise(type(error), error, _stacktrace)
2017-07-02T11:53:47.752505043Z   File "/usr/lib/python3/dist-packages/six.py", line 624, in reraise
2017-07-02T11:53:47.752535355Z     raise value.with_traceback(tb)
2017-07-02T11:53:47.752564886Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 516, in urlopen
2017-07-02T11:53:47.752595719Z     body=body, headers=headers)
2017-07-02T11:53:47.752625146Z   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 333, in _make_request
2017-07-02T11:53:47.752656396Z     httplib_response = conn.getresponse()
2017-07-02T11:53:47.752700511Z   File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
2017-07-02T11:53:47.752731448Z     response.begin()
2017-07-02T11:53:47.752760355Z   File "/usr/lib/python3.4/http/client.py", line 351, in begin
2017-07-02T11:53:47.752790875Z     version, status, reason = self._read_status()
2017-07-02T11:53:47.752829209Z   File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
2017-07-02T11:53:47.752860354Z     raise BadStatusLine(line)
2017-07-02T11:53:47.752889521Z urllib3.exceptions.ProtocolError: ('Connection aborted.', BadStatusLine("''",))
2017-07-02T11:53:47.752920146Z 
2017-07-02T11:53:47.752948063Z During handling of the above exception, another exception occurred:
2017-07-02T11:53:47.752977333Z 
2017-07-02T11:53:47.753005406Z Traceback (most recent call last):
2017-07-02T11:53:47.753034208Z   File "main.py", line 6, in <module>
2017-07-02T11:53:47.753065354Z     apps = OpenHabAppBuilder().buildApps(openhab)
2017-07-02T11:53:47.753094729Z   File "/opt/nuimo-openhab-python/nuimo_openhab/app_builder.py", line 8, in buildApps
2017-07-02T11:53:47.753125510Z     nuimoGroupItem = openhab.req_get("/items/"+rootItemName)
2017-07-02T11:53:47.753156291Z   File "/usr/local/lib/python3.4/dist-packages/openhab/openhab.py", line 91, in req_get
2017-07-02T11:53:47.753187489Z     r = self.session.get(self.base_url + uri_path)
2017-07-02T11:53:47.753217020Z   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 469, in get
2017-07-02T11:53:47.753247593Z     return self.request('GET', url, **kwargs)
2017-07-02T11:53:47.753277229Z   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 457, in request
2017-07-02T11:53:47.753308062Z     resp = self.send(prep, **send_kwargs)
2017-07-02T11:53:47.753337593Z   File "/usr/lib/python3/dist-packages/requests/sessions.py", line 569, in send
2017-07-02T11:53:47.753368010Z     r = adapter.send(request, **kwargs)
2017-07-02T11:53:47.753397332Z   File "/usr/lib/python3/dist-packages/requests/adapters.py", line 407, in send
2017-07-02T11:53:47.753459884Z     raise ConnectionError(err, request=request)
2017-07-02T11:53:47.753490978Z requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))

```

**Comment by pfink** [comment]
It seems like the bluetooth controller is suddenly disappearing as soon as bluetoothctl tries to turn it on: `2017-07-02T11:53:46.739786176Z [bluetooth] [DEL] Controller B8:27:EB:E5:56:F5 raspberrypi [default]`

I also had this issue when using a particular bluetooth adapter. Using another one solved the issue. This is nothing specific from my application (as it already appear even before the app is started). Maybe a bug within bluez or an issue within the hardware. Do you have another adapter that you can test with?

**Comment by pouldam** [comment]
Had an old bluetooh dongle in the drawer (not low energi). Put it in the pi and restartet the container:

```
2017-07-02T12:40:41.453171932Z Starting system message bus: dbus.
2017-07-02T12:40:45.537810258Z Waiting to connect to bluetoothd...
[bluetooth] [NEW] Controller B8:27:EB:E5:56:F5 raspberrypi #1 [default]
[bluetooth] [NEW] Controller 00:1B:DC:0F:AB:E9 raspberrypi
2017-07-02T12:40:45.549092788Z [bluetooth] power on
2017-07-02T12:40:45.552870853Z [bluetooth] [DEL] Controller B8:27:EB:E5:56:F5 raspberrypi #1 [default]
2017-07-02T12:40:45.557279699Z [bluetooth] [DEL] Controller 00:1B:DC:0F:AB:E9 raspberrypi
2017-07-02T12:40:45.560949067Z (bluetoothctl:37): GLib-CRITICAL **: Source ID 24 was not found when attempting to remove it
2017-07-02T12:40:45.582765170Z [bluetooth] Waiting to connect to bluetoothd...
2017-07-02T12:40:46.480460239Z {'openhab_api_url': 'http://192.168.8.10:8444/rest', 'nuimo_mac_address': 'DD:7F:96:8C:06:D3', 'bluetooth_adapter': 'hci0', 'default_gesture_command_mapping': {'TOUCH_RIGHT': 'NEXT', 'BUTTON_RELEASE': 'ON', 'TOUCH_LEFT': 'PREVIOUS', 'TOUCH_BOTTOM': 'OFF'}}
...
...
```

Tried to change bluetooth_adapter in config file to hci1, but that did not make a change.

I am really lost here...

**Comment by pfink** [comment]
Sorry, my support does end at this point as I also do not have the knowledge to fix this. The only advice that I have is that you have to make 100% sure that the bluetooth adapter is not occupied by something else. Regarding the hardware issue, I just decided to spend 10-15€ on a BLE adapter rather than spending hours and hours on bluez / bluetooth debugging. I can just tell you with which BT adapter I tested it successfully:

- https://smile.amazon.de/gp/product/B014UL2926/ref=oh_aui_search_detailpage?ie=UTF8&psc=1
- https://smile.amazon.de/PEARL-Ultrakompakter-USB-Adapter-Bluetooth-Klasse/dp/B00F52EMUC/ref=sr_1_2?s=computers&ie=UTF8&qid=1499000686&sr=1-2&keywords=pearl+bluetooth+4.0

This was the adapter which did NOT work:

- https://smile.amazon.de/gp/product/B01N0368AY/ref=oh_aui_search_detailpage?ie=UTF8&psc=1

I couldn't test the internal BT adapter of RPI3 as I need the UART interface for another purpose and therefore disabled internal bluetooth. 

I'll leave this issue open, so if you or someone else finds a solution, I'd be happy if it could be posted here.

**Comment by pfink** [comment]
Sorry, your problem is maybe not the issue that I had. This is how my log does look like:
```
[NEW] Controller 00:1A7D:DA:71:12 raspberrypi [default]
[NEW] Device E3:CF:56:6A:78:3E Nuimo
[bluetooth]# power on
[DEL] Controller 00:1A:7D:DA:71:12 raspberrypi [default]
[bluetooth]#
(bluetoothctl:31): GLib-CRITICAL **: Source ID 22 was not found when attempting to remove it
\n
```
So I also have the same output even though it works.

Did you make sure that your Nuimo is ready to connect before you started the container?

**Comment by pfink** [comment]
I did setup a Gitter chat for troubleshooting, if you want you can join: https://gitter.im/nuimo-openhab-python/Lobby

**Comment by pouldam** [comment]
Yes - the Nuimo is powered on when I start the container. Our logs look very much alike apart from me missing the 2nd line with the address of the Nuimo.

My Nuimo is blinking with the bluetooth icon in the led-display and continues to do so.

A couple of days ago my Nuimo Android app told me there was a firmware update to the Nuimo which I installed. The Nuimo still connects to the phone, so I have a hard time believing the firmware has broken anything.

**Comment by pfink** [comment]
I think you have to cleanly disconnect your Nuimo from your phone first (it can be done with the Nuimo app). Otherwise Nuimo will not be ready to connect to other devices like the Raspberry. When you do it, please capture how the device behaves (which LEDs you can see) so we can extend the docs afterwards :)

**Comment by pouldam** [comment]
I long pressed the Nuimo instance in the Android app and selected "forget". The Nuimo's display turned black and I could not reactivate it by pressing the Nuimo.

I turned the Nuimo off, switched it on and restarted the container. Sadly, no change. Do you get the checkmark on the Nuimo when it connects to your Pi? Mine keeps blinking the bluetooth icon.

I tried to reboot the Pi and from the Raspbian desktop I tried to scan for bluetooth devices. The Nuimo promptly showed up in the list. I decided not to click "pair" as I am not sure how to make the Nuimo "forget" the Pi.

**Comment by pfink** [comment]
I think "forget" does nothing. Just tried to reconnect Nuimo to the phone while it was connected to the Raspberry first. It's no problem, you just have to stop the docker container.

**Comment by pouldam** [comment]
I don't get the last part of your message: "It's no problem, you just have to stop the docker container".

Was I doing something wrong or are you saying that the thing about letting the phone and Nuimo forget each other is not important after all?

**Comment by pfink** [comment]
I just said that, if you want to reconnect to the phone after you connected to the raspberry, you just have to stop the docker container (just tested it). You could try the following anyway:

# Disconnect Nuimo from the phone (switch within the app should be turned off)
# Press "forget" (just to be 100% sure)
# Start the docker container

**Comment by pouldam** [comment]
Ah, thanks - makes sense.

Anyway - did as you suggested, but no change. I have attached my config.yml... just because. And yes, I have double checked that the Nuimo address is correct.

[config.zip](https://github.com/pfink/nuimo-openhab-python/files/1117874/config.zip)

**Comment by pfink** [comment]
Ohhh, sorry. Now I see within the exception that the issue is not related to your Nuimo, it's related to your openHAB instance. Are sure that your openHAB URL is correct and did you do your openHAB configuration proper? Is the REST API installed on your openHAB instance?

**Comment by pouldam** [comment]
Oh no - I am the one who says 'sorry'! The port for openHAB in my config-file was for accessing openHAB via https and not http. Doh!

Now it works like a charm! Thanks for taking your time to help me.

One thing I learned though that I suggest you add to the readme, is to make sure that the bluetooth service is stopped on the host.

Another minor thing - the log from the Docker container prints a lot of the following lines, when I turn the wheel on the Nuimo. It looks like a hard coded ip address - nothing critical of course:
print("http://192.168.0.31:8080/rest/items/" + self.app.getName() + "/state")

**Comment by pfink** [comment]
Great! Docs are already enhanced, regarding the output, I'll fix it when I add proper logging the application :)
