### ISSUE TITLE
Connection error after successfull connection

### ISSUE THREAD

**Issue by kaikreuzer** [pfink/nuimo-openhab-python#12]
Hey @pfink,

I finally tried it out and got my old Nuimo out of the drawer. 👍 

I've installed everything as described without any errors. But when I start the script, it finds and connects to my Nuimo (it shows the tick mark), but immediately afterwards claims that the connection failed. When I then do some action on Nuimo, events are clearly received, but result in exceptions. See here the log of what happens:

```
[21:14:08] openhabian@openHABianDevice:~/nuimo-openhab-python$ python3 main.py
2020-12-09 21:14:13.519 INFO config - <module>: Loaded config file from config.yml
2020-12-09 21:14:14.603 INFO main - controller_discovered: Discovered Nuimo controller: fa:d9:48:ef:04:dd
2020-12-09 21:14:14.605 INFO main - controller_discovered: Found configured Nuimo with MAC address FA:D9:48:EF:04:DD
2020-12-09 21:14:14.648 INFO app_builder - fetch_sitemap: New/changed sitemap fetched: {'name': 'nuimo', 'label': 'Nuimo', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo', 'homepage': {'id': 'nuimo', 'title': 'Nuimo', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/nuimo', 'leaf': False, 'timeout': False, 'widgets': [{'widgetId': '00', 'type': 'Text', 'visibility': True, 'label': 'Multiroom Audio System', 'icon': 'music', 'mappings': [], 'linkedPage': {'id': '00', 'title': 'Multiroom Audio System', 'icon': 'music', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/00', 'leaf': False, 'timeout': False, 'widgets': [{'widgetId': '0000', 'type': 'Switch', 'visibility': True, 'label': 'AllRooms_Player', 'icon': 'switch', 'mappings': [{'command': 'TOGGLE', 'label': 'BUTTON_CLICK'}], 'widgets': []}, {'widgetId': '0001', 'type': 'Slider', 'visibility': True, 'label': 'AllRooms_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}, {'widgetId': '0002', 'type': 'Text', 'visibility': True, 'label': 'Audio Bedroom', 'icon': 'letterB', 'mappings': [], 'linkedPage': {'id': '0002', 'title': 'Audio Bedroom', 'icon': 'letterB', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/0002', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '000201', 'type': 'Slider', 'visibility': True, 'label': 'Bedroom_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}, {'widgetId': '0003', 'type': 'Text', 'visibility': True, 'label': 'Audio Guest Room', 'icon': 'letterG', 'mappings': [], 'linkedPage': {'id': '0003', 'title': 'Audio Guest Room', 'icon': 'letterG', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/0003', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '000301', 'type': 'Slider', 'visibility': True, 'label': 'GuestRoom_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}]}, 'widgets': []}, {'widgetId': '01', 'type': 'Slider', 'visibility': True, 'label': 'Simple_Light', 'icon': 'light', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}, {'widgetId': '02', 'type': 'Text', 'visibility': True, 'label': 'Simple Light', 'icon': 'letterO', 'mappings': [], 'linkedPage': {'id': '02', 'title': 'Simple Light', 'icon': 'letterO', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/02', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '0200', 'type': 'Switch', 'visibility': True, 'label': 'Simple_Light', 'icon': 'switch', 'mappings': [], 'widgets': []}, {'widgetId': '0201', 'type': 'Slider', 'visibility': True, 'label': 'Simple_Light', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}]}}
2020-12-09 21:14:14.653 INFO model - __init__: Create app: Multiroom Audio System(parent: None)
2020-12-09 21:14:14.655 INFO model - __init__: Create app: Audio Bedroom(parent: <nuimo_menue.model.App object at 0x753b1610>)
2020-12-09 21:14:14.656 INFO model - __init__: Create app: Audio Guest Room(parent: <nuimo_menue.model.App object at 0x753b1610>)
2020-12-09 21:14:14.657 INFO model - __init__: Create app: Simple_Light(parent: None)
2020-12-09 21:14:14.658 INFO model - __init__: Create app: Simple Light(parent: None)
2020-12-09 21:14:14.661 INFO listener - started_connecting: Connecting...
2020-12-09 21:14:27.608 INFO main - initialize_controller: Controller and Listener (re-)initialized!
2020-12-09 21:14:29.193 INFO listener - connect_failed: Connecting failed!
2020-12-09 21:14:37.210 ERROR connection - maybe_handle_message: Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/home/openhabian/.local/lib/python3.7/site-packages/gatt/gatt_linux.py", line 539, in properties_changed
    self.service.device.characteristic_value_updated(characteristic=self, value=bytes(value))
  File "/home/openhabian/.local/lib/python3.7/site-packages/nuimo/nuimo.py", line 233, in characteristic_value_updated
    }[characteristic.uuid](value)
  File "/home/openhabian/.local/lib/python3.7/site-packages/nuimo/nuimo.py", line 268, in _notify_rotation_event
    self._notify_gesture_event(gesture=Gesture.ROTATION, value=rotation_value)
  File "/home/openhabian/.local/lib/python3.7/site-packages/nuimo/nuimo.py", line 280, in _notify_gesture_event
    self.listener.received_gesture_event(GestureEvent(gesture=gesture, value=value))
  File "/home/openhabian/nuimo-openhab-python/nuimo_menue/listener.py", line 28, in received_gesture_event
    raise error
  File "/home/openhabian/nuimo-openhab-python/nuimo_menue/listener.py", line 24, in received_gesture_event
    self.handle_gesture_event(event)
  File "/home/openhabian/nuimo-openhab-python/nuimo_menue/listener.py", line 68, in handle_gesture_event
    gestureResult = self.nuimoMenue.getCurrentApp().getListener().received_gesture_event(event)
  File "/home/openhabian/nuimo-openhab-python/nuimo_openhab/listener.py", line 41, in received_gesture_event
    return self.handleRotation(event)
  File "/home/openhabian/nuimo-openhab-python/nuimo_openhab/listener.py", line 105, in handleRotation
    return self.handleSliders(event.value)
  File "/home/openhabian/nuimo-openhab-python/nuimo_openhab/util/threading.py", line 9, in synced_func
    return func(*args, **kws)
  File "/home/openhabian/nuimo-openhab-python/nuimo_openhab/listener.py", line 121, in handleSliders
    self.openhab.req_post("/items/" + widget["item"]["name"], "REFRESH")
KeyError: 'item'
```

Any idea what might be wrong here?

**Comment by pfink** [comment]
Hi! I noticed this "connection failed" claimed as well on the weekend, have to look into it, but this does not seem to be an issue. The error looks like there is an issue with your sitemap, could you post it, please?

**Comment by kaikreuzer** [comment]
You can see the sitemap in the logfile above:
```
2020-12-09 21:14:14.648 INFO app_builder - fetch_sitemap: New/changed sitemap fetched: {'name': 'nuimo', 'label': 'Nuimo', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo', 'homepage': {'id': 'nuimo', 'title': 'Nuimo', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/nuimo', 'leaf': False, 'timeout': False, 'widgets': [{'widgetId': '00', 'type': 'Text', 'visibility': True, 'label': 'Multiroom Audio System', 'icon': 'music', 'mappings': [], 'linkedPage': {'id': '00', 'title': 'Multiroom Audio System', 'icon': 'music', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/00', 'leaf': False, 'timeout': False, 'widgets': [{'widgetId': '0000', 'type': 'Switch', 'visibility': True, 'label': 'AllRooms_Player', 'icon': 'switch', 'mappings': [{'command': 'TOGGLE', 'label': 'BUTTON_CLICK'}], 'widgets': []}, {'widgetId': '0001', 'type': 'Slider', 'visibility': True, 'label': 'AllRooms_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}, {'widgetId': '0002', 'type': 'Text', 'visibility': True, 'label': 'Audio Bedroom', 'icon': 'letterB', 'mappings': [], 'linkedPage': {'id': '0002', 'title': 'Audio Bedroom', 'icon': 'letterB', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/0002', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '000201', 'type': 'Slider', 'visibility': True, 'label': 'Bedroom_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}, {'widgetId': '0003', 'type': 'Text', 'visibility': True, 'label': 'Audio Guest Room', 'icon': 'letterG', 'mappings': [], 'linkedPage': {'id': '0003', 'title': 'Audio Guest Room', 'icon': 'letterG', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/0003', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '000301', 'type': 'Slider', 'visibility': True, 'label': 'GuestRoom_Volume', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}]}, 'widgets': []}, {'widgetId': '01', 'type': 'Slider', 'visibility': True, 'label': 'Simple_Light', 'icon': 'light', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}, {'widgetId': '02', 'type': 'Text', 'visibility': True, 'label': 'Simple Light', 'icon': 'letterO', 'mappings': [], 'linkedPage': {'id': '02', 'title': 'Simple Light', 'icon': 'letterO', 'link': 'http://192.168.0.4:8080/rest/sitemaps/nuimo/02', 'leaf': True, 'timeout': False, 'widgets': [{'widgetId': '0200', 'type': 'Switch', 'visibility': True, 'label': 'Simple_Light', 'icon': 'switch', 'mappings': [], 'widgets': []}, {'widgetId': '0201', 'type': 'Slider', 'visibility': True, 'label': 'Simple_Light', 'icon': 'slider', 'mappings': [], 'switchSupport': False, 'sendFrequency': 0, 'widgets': []}]}, 'widgets': []}]}}
```
It is EXACTLY the one you have provided in the docs at https://github.com/pfink/nuimo-openhab-python#example-sitemap-configuration.

**Comment by pfink** [comment]
Sorry, I completely forgot to respond! Yes, the log output returns the JSON represantation of the sitemap, but it's always easier to see the actual code.

I think the problem here is that the items you refer to in the sitemap do not exist, otherwise there would be an element "item" in each widget, which is not present. That's why you get the error message `KeyError: 'item'`.

**Comment by kaikreuzer** [comment]
Thanks @pfink, I got it working by providing a proper sitemap with existing items!

So all that is left for this issue is the log message:
```
2020-12-09 21:14:29.193 INFO listener - connect_failed: Connecting failed!
```
that occurs although everything seems to be right.

**Comment by pfink** [comment]
Great! Yes, will keep this issue upon and look into it the next days.

**Comment by pfink** [comment]
Just checked it. The log message is triggered here https://github.com/pfink/nuimo-openhab-python/blob/master/nuimo_menue/listener.py#L93, which is a method not called by my project, but by the nuimo library. It could be somewhere in that library or, probably, even deeper in the bluetooth / BLE stack. It can't be fixed here but I would still let this log message be thrown (with a slight modification to make clear that it's not a final failure), as it is from an API point of view correct, and I hope that it's may fixed one day, e.g. with a newer Bluez version. Anyhow, I won't put further efforts into it and close this issue.

**Comment by kaikreuzer** [comment]
Thanks for the analysis!
